// Auto-generated by build-wasm.sh - do not edit manually
// Sizes measured from the built package; test count read from metrics/doc-metrics.json
export const BUILD_INFO = {
    wasmGzipKB: 1256,
    jsGzipKB: 35,
    crateCount: 4,
    testCount: 3864,
    buildDate: '2026-07-26T19:45:08Z'
};
