// Auto-generated by build-wasm.sh - do not edit manually
// Sizes measured from the built package; test count read from metrics/doc-metrics.json
export const BUILD_INFO = {
    wasmGzipKB: 1262,
    jsGzipKB: 36,
    crateCount: 4,
    testCount: 3872,
    buildDate: '2026-07-26T21:12:09Z'
};
