// Auto-generated by scripts/build-demo-site.sh -- do not edit manually.
// Values are derived from this build and from metrics/doc-metrics.json.
export const BUILD_INFO = {
    wasmGzipKB: 1208,
    jsGzipKB: 34,
    crateCount: 6,
    testCount: 3864,
    buildDate: '2026-07-25T22:32:35Z'
};
